HOST = 'localhost'
# PORT = randint(6000, 7000) # always keeping the same port can cause bind() to fail. Why?
PORT = 6667
PASS ="jambon"
NICK ="a_nick"
USER ="a_username"
LOGIN = "a_login"
REAL_NAME = "Real Name"
CHANNEL = "#test"
